/// <reference types="cypress" />

it('Replenishment of Ukraine mobile phone number', () => {
  cy.visit('https://next.privat24.ua/mobile?lang=en')
    .get('[data-qa-node="phone-number"]')
    .type('931399680')
    .get('[data-qa-node="amount"]')
    .clear()
    .type('1')
    .get('[data-qa-node="numberdebitSource"]')
    .type('4552331448138217')
    .get('[data-qa-node="expiredebitSource"]')
    .type('0524')
    .get('[data-qa-node="cvvdebitSource"]')
    .type('111')
    .get('[data-qa-node="submit"]')
    .click()
    .get('[data-qa-node="card"]')
    .should('have.text', '4552 **** **** 8217')
    .get('div[data-qa-node="amount"]')
    .contains('1 UAH')
    .get('span[data-qa-node="commission"]')
    .should('have.text', '2')
})

it.only('Replenishment of Ukraine mobile phone number', () => {
  cy.visit('https://next.privat24.ua/money-transfer/card')
    .get('[data-qa-node="numberdebitSource"]')
    .type('4552331448138217')
    .get('[data-qa-node="expiredebitSource"]')
    .type('0524')
    .get('[data-qa-node="cvvdebitSource"]')
    .type('111')
    .get('[data-qa-node="numberreceiver"]')
    .type('5309233034765085')
    .get('[data-qa-node="amount"]')
    .type('300')
    .get('[data-qa-node="toggle-comment"]')
    .click()
    .get('[data-qa-node="comment"]')
    .type('Cypress test')
    .get('button[type="submit"]')
    .click()
})